spring.application.name=humanitarian-api
spring.datasource.url=jdbc:postgresql://localhost:5432/hum_db
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true